[package]
name = "rtl-scanner"
version = "0.1.0"
authors = ["Vadim Chekan <kot.begemot@gmail.com>"]

[dependencies]
rtlsdr = "0.1.4"
#qml = "0.0.7"
qml = {git = "https://github.com/White-Oak/qml-rust", rev="6ebb045"}
