[package]
name = "rtl-scanner"
version = "0.1.0"
authors = ["Vadim Chekan <kot.begemot@gmail.com>"]
edition = "2018"

[dependencies]
rtlsdr = {git="https://github.com/vchekan/rtlsdr-rs", rev="0437c44"}
#soapysdr = "0.1.0"

orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }

libc = "0.2.17"
num = "0.2.0"
log = "0.4.6"
simplelog = "0.5.3"

futures = "0.1.25"